---
abstract: 'Optionally queue sub invocations for later.'
author:
  - 'Len Budney <len.budney@grantstreet.com>'
build_requires:
  Test::Exception: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.33
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Sub-Deferrable
provides:
  Sub::Deferrable:
    file: lib/Sub/Deferrable.pm
    version: 0.05
requires:
  perl: 5.008001
resources:
  license: http://dev.perl.org/licenses/
version: 0.05
